### ISSUE TITLE
ES bootstrap node fails to discover initial master nodes

### ISSUE THREAD

**Issue by Bamieh** [BigDataBoutique/elasticsearch-cloud-deploy#106]
Thanks for putting this repo together its a great starting point.

After I've fully setup terraform on AWS I am getting this error:

```
[o.e.c.c.ClusterFormationFailureHelper] [ip-10-0-2-203] master not discovered or elected yet, an election requires two nodes with ids [stw5EG9OStWWlctThr3bsg, EHFb97y9RcqlpoI9_rmwgg], have discovered [{ip-10-0-2-203}{EHFb97y9RcqlpoI9_rmwgg}{xekbFuWCTrikxYXBloW1XQ}{10.0.2.203}{10.0.2.203:9300}{mr}{aws_availability_zone=eu-west-2a, xpack.installed=true, transform.node=false}, {ip-10-0-2-138}{stw5EG9OStWWlctThr3bsg}{s6CwaJeWSj6DMi3EiW5qUw}{10.0.2.138}{10.0.2.138:9300}{lmr}{aws_availability_zone=eu-west-2a, ml.machine_memory=3876032512, ml.max_open_jobs=20, xpack.installed=true, transform.node=false}] which is a quorum; discovery will continue using [10.0.2.138:9300, 10.0.21.70:9300, 10.0.2.138:9300, 10.0.2.102:9300, 10.0.1.46:9300, 10.0.2.203:9300] from hosts providers and [{ip-10-0-2-203}{EHFb97y9RcqlpoI9_rmwgg}{xekbFuWCTrikxYXBloW1XQ}{10.0.2.203}{10.0.2.203:9300}{mr}{aws_availability_zone=eu-west-2a, xpack.installed=true, transform.node=false}] from last-known cluster state; node term 0, last-accepted version 0 in term 0
```

I am not sure where the bootstrap node is getting the ids `stw5EG9OStWWlctThr3bsg` and `EHFb97y9RcqlpoI9_rmwgg` from.

The bootstrap elasticsearch.yml file has the following related configs:

```
cluster.initial_master_nodes: ['ip-10-0-2-203', 'ip-10-0-2-138']
network.host: _ec2:privateIpv4_,localhost
plugin.mandatory: discovery-ec2
cloud.node.auto_attributes: true
cluster.routing.allocation.awareness.attributes: aws_availability_zone
discovery:
    seed_providers: ec2
    ec2.groups: sg-0f3f6cdb1cdc87b05
    ec2.host_type: private_ip
    ec2.tag.Cluster: default-forte-main
    ec2.protocol: http # no need in HTTPS for internal AWS calls
    # manually set the endpoint because of auto-discovery issues
    # https://github.com/elastic/elasticsearch/issues/27464
    ec2.endpoint: ec2.eu-west-2.amazonaws.com
node.master: true
node.data: false
node.ingest: false
```

All nodes have the `hostname` as their `node.name` for discovery as stated here in the es docs (https://www.elastic.co/guide/en/elasticsearch/reference/master/modules-discovery-bootstrap-cluster.html#modules-discovery-bootstrap-cluster-fqdns)
