### ISSUE TITLE
Packer hang's on building ES (grub-pc)

### ISSUE THREAD

**Issue by moesy** [BigDataBoutique/elasticsearch-cloud-deploy#27]
Packer hangs when running the build command for elasticsearch

```
    amazon-ebs: Setting up grub2-common (2.02~beta2-36ubuntu3.16) ...
    amazon-ebs: Setting up grub-pc-bin (2.02~beta2-36ubuntu3.16) ...
    amazon-ebs: Setting up grub-pc (2.02~beta2-36ubuntu3.16) ...
    amazon-ebs: debconf: unable to initialize frontend: Dialog
    amazon-ebs: debconf: (Dialog frontend will not work on a dumb terminal, an emacs shell buffer, or without a controlling terminal.)
    amazon-ebs: debconf: falling back to frontend: Readline
    amazon-ebs: Configuring grub-pc
    amazon-ebs: -------------------
    amazon-ebs:
    amazon-ebs: A new version (/tmp/grub.ZtqN4eeYBC) of configuration file /etc/default/grub is
    amazon-ebs: available, but the version installed currently has been locally modified.
    amazon-ebs:
    amazon-ebs:   1. install the package maintainer's version
    amazon-ebs:   2. keep the local version currently installed
    amazon-ebs:   3. show the differences between the versions
    amazon-ebs:   4. show a side-by-side difference between the versions
    amazon-ebs:   5. show a 3-way difference between available versions
    amazon-ebs:   6. do a 3-way merge between available versions (experimental)
    amazon-ebs:   7. start a new shell to examine the situation
    amazon-ebs:
```

Workaround
- comment out grub and upgrade lines from update_machine.sh
